### ISSUE TITLE
Support building projects

### ISSUE THREAD

**Issue by jonsterling** [freebroccolo/vscode-sml#1]
It would be nice to support building projects upon save, and displaying diagnostics. Now, there are basically three SML implementations which see any amount of use:

1. SML/NJ
2. MLton
3. Poly/ML

It might be worthwhile to support Poly/ML, but I don't know enough about it—I think only the Isabelle people use it. It's probably not worth doing anything special for MLton, since 1) it's too slow to use for development, and 2) you just run a command in the shell, there's no interactive or incremental compilation.

That leaves SML/NJ. SML/NJ projects are typically organized around a `.cm` file, which specifies the files to build (and, optionally, the top-level identifiers to export). You build an SML project by entering the repl (running `sml`) and then typing `CM.make "my-project.cm";`. The usual way to work with SML/NJ is to just run this command repeatedly again and again as you are editing your code.

What would be cool is if you could specify (perhaps in the root directory of your project) the name of a master `.cm` file, and then every time you save something in VS Code, it would send `CM.make "my-project.cm";` to a REPL process or something like that.

**Comment by freebroccolo** [comment]
Hmm, interesting. So for SML/NJ you basically need to keep the REPL process running in order to make this useful? Is that how the emacs modes work?

Is there a convention for standard names for the `.cm` files? Would it be reasonable to just run the command for all of the ones found in the root directory?

**Comment by jonsterling** [comment]
@freebroccolo You don't technically have to keep the repl running; you can run `sml welp.cm`, I think, but this will open a repl which you must close.

I don't think there is really any convention for standard names sadly—at least in my projects (which, sadly, probably make up a pretty big proportion of the *actively-developed* SML ecosystem), I tend to have a few different `.cm` files, some of which require configuration (e.g. setting path anchors for dependencies) and others which are suitable for development. The latter I personally always call `development.cm`, but I think I may be the only person who does this.

**Comment by freebroccolo** [comment]
I see, makes sense.

I think maybe the thing to do here is to allow some sort of JSON project file where the `.cm` files can be specified. We could have the mode check for that file and if it's not found maybe show a prompt asking the user to create one. We could use that file for other project related settings too.
